### ISSUE TITLE
Problem initiating a sell order

### ISSUE THREAD

**Issue by gogogadget-test** [sellerscrisp/binance-quick-buy#1]
Hi
I got this error, maybe someone can help me? Script bought KAVA coin for BTC, but it didn't sell it.
![2021-02-09 (1)](https://user-images.githubusercontent.com/78539805/107400218-e53c3680-6b01-11eb-9e56-80b363e5ab6a.png)

**Comment by sellerscrisp** [comment]
I have yet to get the limit sell feature to work properly. I don't have enough time to continue working on this project in the foreseeable future, but if you want to submit a pull request and update it feel free to do so! Found a similar issue in the python-binance repo [#139](https://github.com/sammchardy/python-binance/issues/139).
