### ISSUE TITLE
change buying coin 

### ISSUE THREAD

**Issue by m3a4s** [sellerscrisp/binance-quick-buy#2]
how can i change buying coin ? , i want to buy BTC using USDT 
And selling BTC and get my profit in USDT 

Thanks

**Comment by sellerscrisp** [comment]
I believe you could change the ``` 'BTC' ``` to your desired coin on this line [here](https://github.com/sellerscrisp/binance-quick-buy/blob/11b50eaf1d42af9381e4e331fdaa3514d60bcbd9/main.py#L34). I have yet to test this but make sure you have the proper funds in your wallet.

**Comment by m3a4s** [comment]
thank you for your replay , but in case i have USDT and i want to make this program Buying Ethereum
What should i change ?

**Comment by sellerscrisp** [comment]
> thank you for your replay , but in case i have USDT and i want to make this program Buying Ethereum
> What should i change ?

If Binane allows you to purchase BTC with USDT you would only need to change ```'BTC'``` on the line I previously mentioned. Then, run the program and you will be prompted with which coin you would like to purchase. Enter ```USDT``` into the input and you should be good.
